### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [dfmalacarne/QGIS_FHR_data#4]
@dfmalacarne Can you please remove the __pycache folder it is autogenerated on install

**Comment by dfmalacarne** [comment]
Thanks @NyakudyaA. The zip I uploaded on QGIS Python Plugins Repository was already without __pycache__ folder, I forgot to remove it from GitHub, now is done.

**Comment by NyakudyaA** [comment]
LGTM
